"use client";
import { useCallback, useEffect, useState } from "react";
import { resaRequest } from "@/lib/resa/api";
type Organization = { id: string; name: string };
type RequestItem = { id: string; service_type: string; status: string; subject: string; applicant_user_id: string; applicant_notes?: string; details?: Record<string, unknown>; created_at: string; organization?: { id: string; name: string }; destination?: { id: string; name: string } };
const labels: Record<string, string> = { MEMBERSHIP_TRANSFER: "Transferência de membro", RECOMMENDATION_LETTER: "Carta de recomendação", CHILD_DEDICATION: "Dedicação de criança", BAPTISM_REQUEST: "Pedido de batismo", PASTORAL_VISIT: "Visita pastoral", GENERAL_SECRETARY_SERVICE: "Outro serviço" };
export default function SecretaryPage() { const [orgs, setOrgs] = useState<Organization[]>([]); const [orgId, setOrgId] = useState(""); const [items, setItems] = useState<RequestItem[]>([]); const [message, setMessage] = useState("A carregar a secretaria…"); const [busy, setBusy] = useState(false);
  const load = useCallback(async (id = orgId) => { if (!id) return; try { setItems(await resaRequest<RequestItem[]>(`/v1/member-services/inbox?organization_id=${id}`)); setMessage(""); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Não foi possível carregar a caixa da secretaria."); } }, [orgId]);
  useEffect(() => { const timer = window.setTimeout(async () => { try { const result = await resaRequest<Organization[]>("/v1/organizations"); setOrgs(result); if (result[0]) setOrgId(result[0].id); else setMessage("Nenhuma organização administrada encontrada."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Não foi possível carregar as organizações."); } }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function update(id: string, status: "IN_REVIEW" | "APPROVED" | "REJECTED" | "COMPLETED") { setBusy(true); try { await resaRequest(`/v1/member-services/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Não foi possível atualizar o pedido."); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-slate-100 p-8"><div className="mx-auto max-w-6xl space-y-8"><header className="rounded-3xl bg-[#0C1A3D] p-8 text-white shadow-xl"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#D4AF37]">Secretary office</p><h1 className="mt-3 text-4xl font-bold">Caixa da Secretaria</h1><p className="mt-3 max-w-3xl text-white/70">Reveja pedidos dos membros com rastreabilidade e fluxo de aprovação.</p><select value={orgId} onChange={(event) => setOrgId(event.target.value)} className="mt-5 rounded-xl px-4 py-3 text-[#0C1A3D]"><option value="">Selecione a organização</option>{orgs.map((org) => <option key={org.id} value={org.id}>{org.name}</option>)}</select></header>{message && <div className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-600">{message}</div>}<section className="space-y-5">{items.map((item) => <article key={item.id} className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#8B6F16]">{labels[item.service_type] ?? item.service_type}</p><h2 className="mt-2 text-xl font-bold text-[#0C1A3D]">{item.subject}</h2><p className="mt-2 text-sm text-slate-500">Membro: {item.applicant_user_id}</p><p className="text-sm text-slate-500">Origem: {item.organization?.name}{item.destination ? ` · Destino: ${item.destination.name}` : ""}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">{item.status}</span></div>{item.applicant_notes && <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-700"><strong>Mensagem:</strong> {item.applicant_notes}</div>}{item.details && Object.keys(item.details).length > 0 && <pre className="mt-4 overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs text-emerald-200">{JSON.stringify(item.details, null, 2)}</pre>}<div className="mt-5 flex flex-wrap gap-3">{item.status === "SUBMITTED" && <button disabled={busy} onClick={() => void update(item.id, "IN_REVIEW")} className="rounded-xl bg-[#0C1A3D] px-4 py-2 text-sm font-semibold text-white">Assumir revisão</button>}{["SUBMITTED", "IN_REVIEW"].includes(item.status) && <><button disabled={busy} onClick={() => void update(item.id, "APPROVED")} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Aprovar</button><button disabled={busy} onClick={() => void update(item.id, "REJECTED")} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Rejeitar</button></>}{item.status === "APPROVED" && <button disabled={busy} onClick={() => void update(item.id, "COMPLETED")} className="rounded-xl bg-[#D4AF37] px-4 py-2 text-sm font-semibold text-[#0C1A3D]">Marcar concluído</button>}</div></article>)}{!items.length && <div className="rounded-3xl bg-white p-8 text-slate-500">Não existem pedidos pendentes para esta organização.</div>}</section></div></main>; }
