"use client";

import { useState } from "react";
import { resaRequest } from "@/lib/resa/api";

export default function CreateCommunity() {
  const [name,setName]=useState(""); const [type,setType]=useState("church"); const [description,setDescription]=useState(""); const [status,setStatus]=useState<"idle"|"saving"|"success"|"error">("idle"); const [message,setMessage]=useState("");
  async function createCommunity(){if(name.trim().length<2){setStatus("error");setMessage("Defina o nome da comunidade.");return;}setStatus("saving");setMessage("");const slug=name.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");try{await resaRequest("/v1/resa/communities",{method:"POST",body:JSON.stringify({name:name.trim(),slug,description:description.trim()||null,visibility:"public"})});setStatus("success");setMessage("Comunidade criada.");setName("");setDescription("");}catch(e){setStatus("error");setMessage(e instanceof Error?e.message:"Não foi possível criar a comunidade.");}}
  return <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_18px_50px_rgba(15,23,42,0.08)] sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">RESA · Comunidades</p><h2 className="mt-2 text-2xl font-semibold text-[#0C1A3D]">Criar comunidade</h2><div className="mt-6 grid gap-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da comunidade" className="rounded-2xl border border-slate-200 px-4 py-3"/><select value={type} onChange={e=>setType(e.target.value)} className="rounded-2xl border border-slate-200 px-4 py-3"><option value="church">Igreja Local</option><option value="department">Departamento</option><option value="ministry">Ministério</option><option value="small-group">Pequeno Grupo</option><option value="interest">Comunidade de Interesse</option></select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição da comunidade" rows={5} className="rounded-2xl border border-slate-200 px-4 py-3"/></div>{message&&<p role={status==="error"?"alert":"status"} className={`mt-4 rounded-2xl p-3 text-sm ${status==="error"?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{message}</p>}<button disabled={status==="saving"} onClick={()=>void createCommunity()} className="mt-5 rounded-2xl bg-[#0C1A3D] px-6 py-3 text-sm font-semibold text-white disabled:opacity-60">{status==="saving"?"A criar…":"Criar comunidade"}</button></section>;
}